ifndef DPP_ROOT
$(error DPP_ROOT is undefined)
endif

include $(DPP_ROOT)/Makefile.inc

DRIVER_NAME = driver-kmem
DRIVER_OBJECTS = $(DRIVER_NAME).o memory.o
DRIVER_TARGET = $(DRIVER_NAME).sys

TARKOV_NAME = tfk
TARKOV_OBJECTS = tarkov.o memory.o
TARKOV_TARGET = $(TARKOV_NAME).sys

all: $(DRIVER_TARGET) $(TARKOV_TARGET)

install: $(DRIVER_TARGET) $(TARKOV_TARGET)
	$(call INSTALL_EXEC_SIGN,$(DRIVER_TARGET))
	$(INSTALL) $(DRIVER_NAME).bat $(DESTDIR)
	$(call INSTALL_EXEC_SIGN,$(TARKOV_TARGET))
	$(INSTALL) $(TARKOV_NAME).bat $(DESTDIR)

clean:
	rm -f $(DRIVER_OBJECTS) $(DRIVER_TARGET)
	rm -f $(TARKOV_OBJECTS) $(TARKOV_TARGET)

%.o: %.cpp
	$(call BUILD_CPP_OBJECT,$<,$@)

$(DRIVER_TARGET): $(DRIVER_OBJECTS)
	$(call LINK_CPP_KERNEL_TARGET,$(DRIVER_OBJECTS),$@)

$(TARKOV_TARGET): $(TARKOV_OBJECTS)
	$(call LINK_CPP_KERNEL_TARGET,$(TARKOV_OBJECTS),$@)
